kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: repo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp3
  volumeMode: Filesystem
